### ISSUE TITLE
Add a group model

### ISSUE THREAD

**Issue by jkoestinger** [smartfactory-gmbh/brolga#26]
**Is your feature request related to a problem? Please describe.**
Currently you can only add monitors to the list without any way of grouping them (tags are not really the same imo).

**Describe the solution you'd like**
It may be interesting to add a MonitorGroup model that allows to gather together existing monitors, and define common alert rules

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by rluechinger** [comment]
Maybe this could be combined with https://github.com/smartfactory-gmbh/brolga/issues/49: each group gets an additional slug which serves a dashboard with this group's monitors only.

**Comment by jkoestinger** [comment]
Closing as this means the groups are getting really close semantically to the tags, so we can probably use the tags directly
