### ISSUE TITLE
Overview of all prod systems

### ISSUE THREAD

**Issue by JulianeSMF** [smartfactory-gmbh/brolga#49]
Current behaviour
- there is one monitoring dashboard for all systems (https://brolga.smf.ai/monitors)

Feature request 
- add an additional monitoring dashboard (maybe https://brolga.smf.ai/monitors-prod?) where only prod systems are shown

A Dashboard for "only test system" would also be nice, but the prod systems are the most important systems, so it would really help to have an overview of only the prod systems.

**Comment by jkoestinger** [comment]
I'm assuming at some point the tags will be something dynamic (users will be able to add custom ones). In that case, I guess we could have some sort of generalized dashboard view, where a filter can be set by default (i.e. per tag)?

**Comment by rluechinger** [comment]
Looking across the fence, https://github.com/louislam/uptime-kuma allows users to create any number of dashboards. Each of these dashboards consists of:
- A user-defined slug
- A selection of monitors to display

I really like that approach!

**Comment by jkoestinger** [comment]
Then we could add a new dashboard model to accommodate this. Probably we should also come up with a way to order the monitors, or we could stick with alphabetical order for now
